# Generated by Django 3.2.1 on 2023-01-27 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_transactions_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 27, 6, 20, 49, 664715)),
        ),
    ]
